FROM node:20-alpine AS builder
WORKDIR /build

ARG VITE_APP_BASE_API=/prod-api
ARG VITE_APP_ONLYOFFICE_API=http://117.72.79.75:8080/web-apps/apps/api/documents/api.js
ARG VITE_APP_MINIO_URL=http://117.72.79.75:9001

COPY compserve-ui/package.json compserve-ui/package-lock.json ./
RUN npm config set registry https://registry.npmmirror.com && npm ci

COPY compserve-ui/ ./

ENV VITE_APP_BASE_API=${VITE_APP_BASE_API}
ENV VITE_APP_ONLYOFFICE_API=${VITE_APP_ONLYOFFICE_API}
ENV VITE_APP_MINIO_URL=${VITE_APP_MINIO_URL}

RUN npm run build:prod

FROM nginx:1.27-alpine
COPY deploy/docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /build/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

